# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements_dev.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox


